### PR TITLE
added filling of max and min range according to current filtered scan ranges

### PR DESCRIPTION
**Pull request by dettmann**

### CODE REVIEW

**Comment by jmachowinski** [comment]
I don't get the idea of this patch min and max Range arte static parameters of the Hardware. Why would you fill them with values ?

**Comment by dettmann** [comment]
Well, the laser_scanner is already providing the hardware specific min and max values. In contrast, the laser_filter is more abstract and actually modifies the the laser scan values. Why should this component not add useful information which could decrease computation time on potentially following modules?

**Comment by jmachowinski** [comment]
The min and max ranges are used to filter out invalid measurements. Changing the meaning of this, would break the convertScanToPointCloud method. As this is a component based approach, a component would never know, if it is directly connected to the hardware or, to the filter. Therefore a change of behaviour without changing the type is a bad idea.

**Comment by dettmann** [comment]
But the laser_filter is already excluding invalid measurements, right? Then, i don't see the point of using the theoretical min and max distance of the sensor rather than the limits of the current scanned values.

**Comment by jmachowinski** [comment]
laser_filter sets filtered points to an invalid_range ( < minRange). It is not possible to remove any measurements from the ranges vector. If you do that, you can't recalculate the scanning angle. 
Invalid is <= minRange and >= maxRange. If you set min and max to real values, you discard at least two valid measurements.

**Pull request closed without merging**
